custom_rules:
  no_import_in_domain:
    name: "No Restricted Imports in Domain"
    regex: '^import\s+\w+' # Matches any 'import ModuleName'
    message: "Domain module should not import UIKit, Foundation, or infrastructure layers."
    severity: error
excluded:
  - Tests/DomainLayerTests
included:
  - Sources/DomainLayer
