custom_rules:
  no_import_in_domain:
    name: "No Restricted Imports in Presentation"
    regex: 'import (DataLayer)'
    message: "Presentation module should not import Data layers."
    severity: error
    excluded: # Optional: Exclude specific directories or files
      - Tests/PresentationLayerTests
    included: # Restrict to your domain module
      - Sources/PresentationLayer


