custom_rules:
  no_import_in_domain:
    name: "No Restricted Imports in Presentation"
    regex: 'import (DataLayer)'
    message: "Presentation module should not import Data layers."
    severity: error
excluded:
  - Tests/PresentationLayerTests
included:
  - Sources/PresentationLayer


