custom_rules:
  no_import_in_domain:
    name: "No Restricted Imports in Infrastructure"
    regex: 'import (PresentationLayer|DataLayer)'
    message: "Domain module should not import Presentation layers."
    severity: error
excluded:
  - Tests/InfrastructureLayerTests
included:
  - Sources/InfrastructureLayer
