custom_rules:
  no_import_in_domain:
    name: "No Restricted Imports in Infrastructure"
    regex: 'import (PresentationLayer|DataLayer)'
    message: "Domain module should not import Presentation layers."
    severity: error
    excluded: # Optional: Exclude specific directories or files
      - Tests/InfrastructureLayerTests
    included: # Restrict to your domain module
      - Sources/InfrastructureLayer
